spring:
  application:
    name: itda

  mail:
    protocol: smtp
    host: ${mail_host}
    port: 587
    username: ${mail_username}
    password: ${mail_password}
    default-encoding: UTF-8
    properties:
      mail.debug: true
      mail.smtp:
        auth: true
        timeout: 5000
        starttls:
          enable: true
          required: true

  sql:
    init:
      data-locations: classpath:db/init/*.sql

logging:
  level:
    root: info
    pe.goblin.itda: debug
    org.mybatis: debug
    org.apache.ibatis.type: debug
    org.springframework.jdbc: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: pe.goblin.itda.common.mybatis.typehandler
